name: Package and Upload Executable on release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: src

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/windows/netconfparser.exe