name: Release Please

on:
  push:
    branches:
      - master
      - workflows

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          release-type: python
          target-branch: ${{ github.ref_name }}
          # component: netconfparser #not needed since single component